# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
 - openjdk14

#services:
#  - postgresql

#before_install:
#  - psql -c 'create database name_db;' -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -roman.sercent@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="22821c4c-9963-4816-823d-a77f10e42637"